[package]
name = "cp-mod-console"
version = "0.1.0"
edition = "2024"

[dependencies]
cp-base.workspace = true
ratatui.workspace = true
crossterm.workspace = true
serde.workspace = true
serde_json.workspace = true
