[package]
name = "cp-mod-firecrawl"
version = "0.1.0"
edition = "2024"

[dependencies]
cp-base.workspace = true
reqwest = { workspace = true }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
